#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${AIRFLOW_DB_USER} WITH PASSWORD '${AIRFLOW_DB_PASSWORD}';
  CREATE DATABASE ${AIRFLOW_DB} OWNER ${AIRFLOW_DB_USER};

  CREATE USER ${POLARIS_DB_USER} WITH PASSWORD '${POLARIS_DB_PASSWORD}';
  CREATE DATABASE ${POLARIS_DB} OWNER ${POLARIS_DB_USER};

  CREATE USER ${TRINO_DB_USER} WITH PASSWORD '${TRINO_DB_PASSWORD}';
  CREATE DATABASE ${TRINO_DB} OWNER ${TRINO_DB_USER};
EOSQL